version: '3.5'

services:
  walnut:
    container_name: walnut
    image: timkaufmann/watch-ocrmypdf:latest
    volumes:
      - /mnt/public/Automagisch:/consume
      - /root/git/docker-watch-ocrmypdf/scripts:/scripts
    environment:
      - CLOUD_TAQUIRI_PATH=${CLOUD_TAQUIRI_PATH}
      - CLOUD_TAQUIRI_USER=${CLOUD_TAQUIRI_USER}
      - CLOUD_TAQUIRI_PASS=${CLOUD_TAQUIRI_PASS}
      - CLOUD_STB_PATH=${CLOUD_STB_PATH}
      - CLOUD_STB_USER=${CLOUD_STB_USER}
      - CLOUD_STB_PASS=${CLOUD_STB_PASS}
      - WOCR_SCRIPT_Scanner=/scripts/scanner-script.sh
      - WOCR_SCRIPT_TQAusgangsrechnungen=/scripts/tq-ausgangsrechnungen-script.sh
