version: '3.5'

services:
  ocrmypdf:
    container_name: ocrmypdf
    image: timkaufmann/watch-ocrmypdf:latest
    volumes:
      - /mnt/public/Scanner:/consume
    environment:
      - NEXTCLOUD_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_PATH=${NEXTCLOUD_PATH}
      - WOCR_AFTERCMD=/copy.sh "%FULLFILE%" "%FILENAME%"
      - WOCR_CMD=ocrmypdf -l eng+deu --rotate-pages --deskew --clean --skip-text --clean-final --jobs 2 --output-type pdfa --jbig2-lossy --optimize 3 %INFILE% %OUTFILE%
      # - WOCR_CMD_onlyocr=ocrmypdf -l eng+deu --rotate-pages --jobs 2 --output-type pdfa %INFILE% %OUTFILE%
